// Code generated by sql2gorm. DO NOT EDIT.
package model

// 用户会员
type UserMember struct {
	MemberId  int64  `gorm:"column:member_id;type:bigint(20) unsigned;primary_key;AUTO_INCREMENT" json:"member_id"`
	Nickname  string `gorm:"column:nickname;type:varchar(50);NOT NULL" json:"nickname"`           // 用户昵称
	Id        string `gorm:"column:id;type:varchar(20);NOT NULL" json:"id"`                       // ID, 对用户展示并且唯一
	Gender    string `gorm:"column:gender;type:char(5);default:wz;NOT NULL" json:"gender"`        // wz-未知, w-女, m-男, z-中性
	Birthdate int    `gorm:"column:birthdate;type:int(11);default:0;NOT NULL" json:"birthdate"`   // 出生日期
	Avatar    string `gorm:"column:avatar;type:varchar(255);NOT NULL" json:"avatar"`              // 头像
	Signature string `gorm:"column:signature;type:varchar(64);NOT NULL" json:"signature"`         // 个性签名
	City      string `gorm:"column:city;type:char(50);NOT NULL" json:"city"`                      // 城市
	Province  string `gorm:"column:province;type:char(50);NOT NULL" json:"province"`              // 省份
	CreatedAt int    `gorm:"autoCreateTime;column:created_at;type:int(11)" json:"created_at"`     // 添加时间
	UpdatedAt int    `gorm:"autoUpdateTime;column:updated_at;type:int(11)" json:"updated_at"`     // 修改时间
	DeletedAt int    `gorm:"column:deleted_at;type:int(11);default:0;NOT NULL" json:"deleted_at"` // 删除时间
}

func (m *UserMember) TableName() string {
	return "user_member"
}
